# [ADDED v2026.9.19] Seed data for db_items_categories.
#
# This is the exact content and ordering of the old frontend
# organizer-data.js, moved here so the categories live in the database
# instead of in a shipped JavaScript file. Keeping the original order
# matters: existing inventory references these names, and the dropdowns
# should look unchanged to anyone upgrading.
#
# Written once, on first run. After that the table is the source of
# truth and this list is never consulted again, so a HACS update can
# never overwrite a category the user added or renamed.
DEFAULT_CATEGORIES = [
    ('Food', 'Dairy', 'Units', 0, 0),
    ('Food', 'Eggs', 'Units', 0, 1),
    ('Food', 'Meat', 'Kg', 0, 2),
    ('Food', 'Poultry', 'Kg', 0, 3),
    ('Food', 'Fish', 'Kg', 0, 4),
    ('Food', 'Vegetables', 'Kg', 0, 5),
    ('Food', 'Fruits', 'Kg', 0, 6),
    ('Food', 'Pantry', 'Kg', 0, 7),
    ('Food', 'Dry Goods', 'Kg', 0, 8),
    ('Food', 'Carbs', 'Kg', 0, 9),
    ('Food', 'Legumes', 'Kg', 0, 10),
    ('Food', 'Spices', 'g', 0, 11),
    ('Food', 'Baking Goods', 'g', 0, 12),
    ('Food', 'Sauces', 'Units', 0, 13),
    ('Food', 'Spreads', 'Units', 0, 14),
    ('Food', 'Canned Goods', 'Units', 0, 15),
    ('Food', 'Bread', 'Units', 0, 16),
    ('Food', 'Pastries', 'Units', 0, 17),
    ('Food', 'Beverages', 'Liter', 0, 18),
    ('Food', 'Snacks', 'Units', 0, 19),
    ('Food', 'Sweets', 'Units', 0, 20),
    ('Food', 'Dietary Supplements', 'Units', 0, 21),
    ('Food', 'Vitamins', 'Units', 0, 22),
    ('Cleaning', 'General Cleaning', 'Liter', 1, 0),
    ('Cleaning', 'Laundry', 'Liter', 1, 1),
    ('Cleaning', 'Dishwashing', 'Units', 1, 2),
    ('Cleaning', 'Accessories', 'Units', 1, 3),
    ('Cleaning', 'Consumables', 'Units', 1, 4),
    ('Home Maintenance', 'General Cleaning', 'Liter', 2, 0),
    ('Home Maintenance', 'Laundry', 'Liter', 2, 1),
    ('Home Maintenance', 'Dishwashing', 'Units', 2, 2),
    ('Home Maintenance', 'Accessories', 'Units', 2, 3),
    ('Home Maintenance', 'Consumables', 'Units', 2, 4),
    ('Home Maintenance', 'Hand Tools', 'Units', 2, 5),
    ('Home Maintenance', 'Materials', 'Units', 2, 6),
    ('Home Maintenance', 'Power Tools', 'Units', 2, 7),
    ('Toiletries', 'Personal Hygiene', 'Units', 3, 0),
    ('Toiletries', 'Paper Products', 'Units', 3, 1),
    ('Toiletries', 'First Aid', 'Units', 3, 2),
    ('Toiletries', 'OTC Medicines', 'Units', 3, 3),
    ('Pharmacy', 'Personal Hygiene', 'Units', 4, 0),
    ('Pharmacy', 'Paper Products', 'Units', 4, 1),
    ('Pharmacy', 'First Aid', 'Units', 4, 2),
    ('Pharmacy', 'OTC Medicines', 'Units', 4, 3),
    ('General Supplies', 'Electrical', 'Units', 5, 0),
    ('General Supplies', 'Lighting', 'Units', 5, 1),
    ('General Supplies', 'Miscellaneous', 'Units', 5, 2),
    ('General Supplies', 'Maintenance', 'Units', 5, 3),
    ('General Supplies', 'Stationery', 'Units', 5, 4),
    ('General Supplies', 'Desk Supplies', 'Units', 5, 5),
    ('Home Office Supplies', 'Electrical', 'Units', 6, 0),
    ('Home Office Supplies', 'Lighting', 'Units', 6, 1),
    ('Home Office Supplies', 'Miscellaneous', 'Units', 6, 2),
    ('Home Office Supplies', 'Maintenance', 'Units', 6, 3),
    ('Home Office Supplies', 'Stationery', 'Units', 6, 4),
    ('Home Office Supplies', 'Desk Supplies', 'Units', 6, 5),
    ('Tools', 'Hand Tools', 'Units', 7, 0),
    ('Tools', 'Materials', 'Units', 7, 1),
    ('Tools', 'Accessories', 'Units', 7, 2),
    ('Tools', 'Power Tools', 'Units', 7, 3),
    ('Medicines', 'Pain Relievers', 'Units', 8, 0),
    ('Medicines', 'Fever Reducers', 'Units', 8, 1),
    ('Medicines', 'First Aid Supplies', 'Units', 8, 2),
    ('Medicines', 'Topical Treatments', 'Units', 8, 3),
    ('Medicines', 'Ointments', 'Units', 8, 4),
    ('Medicines', 'Miscellaneous', 'Units', 8, 5),
    ('Medicines', 'Winter Illnesses', 'Units', 8, 6),
    ('First Aid', 'Pain Relievers', 'Units', 9, 0),
    ('First Aid', 'Fever Reducers', 'Units', 9, 1),
    ('First Aid', 'First Aid Supplies', 'Units', 9, 2),
    ('First Aid', 'Topical Treatments', 'Units', 9, 3),
    ('First Aid', 'Ointments', 'Units', 9, 4),
    ('First Aid', 'Miscellaneous', 'Units', 9, 5),
    ('First Aid', 'Winter Illnesses', 'Units', 9, 6),
    ('Kitchenware', 'Pots', 'Units', 10, 0),
    ('Kitchenware', 'Pans', 'Units', 10, 1),
    ('Kitchenware', 'Dinnerware', 'Units', 10, 2),
    ('Kitchenware', 'Serving', 'Units', 10, 3),
    ('Kitchenware', 'Cooking Accessories', 'Units', 10, 4),
    ('Kitchenware', 'Baking Accessories', 'Units', 10, 5),
    ('Kitchenware', 'Cutting Accessories', 'Units', 10, 6),
    ('Kitchenware', 'Storage', 'Units', 10, 7),
    ('Kitchenware', 'Organization', 'Units', 10, 8),
    ('Kitchenware', 'Small Kitchen Appliances', 'Units', 10, 9),
    ('Electronics', 'Entertainment', 'Units', 11, 0),
    ('Electronics', 'Computing', 'Units', 11, 1),
    ('Electronics', 'Major Appliances', 'Units', 11, 2),
    ('Electronics', 'Small Home Appliances', 'Units', 11, 3),
    ('Electronics', 'Smart Tech', 'Units', 11, 4),
    ('Entertainment', 'Entertainment', 'Units', 12, 0),
    ('Entertainment', 'Computing', 'Units', 12, 1),
    ('Entertainment', 'Major Appliances', 'Units', 12, 2),
    ('Entertainment', 'Small Home Appliances', 'Units', 12, 3),
    ('Entertainment', 'Smart Tech', 'Units', 12, 4),
    ('Clothing', 'Everyday Clothing', 'Units', 13, 0),
    ('Clothing', 'Intimates', 'Units', 13, 1),
    ('Clothing', 'Loungewear', 'Units', 13, 2),
    ('Clothing', 'Winter Clothing', 'Units', 13, 3),
    ('Clothing', 'Transitional Clothing', 'Units', 13, 4),
    ('Clothing', 'Footwear', 'Units', 13, 5),
    ('Clothing', 'Accessories', 'Units', 13, 6),
    ('Footwear', 'Everyday Clothing', 'Units', 14, 0),
    ('Footwear', 'Intimates', 'Units', 14, 1),
    ('Footwear', 'Loungewear', 'Units', 14, 2),
    ('Footwear', 'Winter Clothing', 'Units', 14, 3),
    ('Footwear', 'Transitional Clothing', 'Units', 14, 4),
    ('Footwear', 'Footwear', 'Units', 14, 5),
    ('Footwear', 'Accessories', 'Units', 14, 6),
    ('Home Textiles', 'Bed Linens', 'Units', 15, 0),
    ('Home Textiles', 'Bath Textiles', 'Units', 15, 1),
    ('Home Textiles', 'Kitchen Textiles', 'Units', 15, 2),
    ('Bedding', 'Bed Linens', 'Units', 16, 0),
    ('Bedding', 'Bath Textiles', 'Units', 16, 1),
    ('Bedding', 'Kitchen Textiles', 'Units', 16, 2),
    ('Pet Supplies', 'Food', 'Kg', 17, 0),
    ('Pet Supplies', 'Feeding', 'Kg', 17, 1),
    ('Pet Supplies', 'Care', 'Units', 17, 2),
    ('Pet Supplies', 'Accessories', 'Units', 17, 3),
    ('Baby Supplies', 'Feeding', 'Units', 18, 0),
    ('Baby Supplies', 'Nursing', 'Units', 18, 1),
    ('Baby Supplies', 'Diapering', 'Units', 18, 2),
    ('Baby Supplies', 'Hygiene', 'Units', 18, 3),
    ('Baby Supplies', 'Gear', 'Units', 18, 4),
    ('Baby Supplies', 'Travel', 'Units', 18, 5),
    ('Outdoor', 'Gardening Tools', 'Units', 19, 0),
    ('Outdoor', 'Outdoor Maintenance', 'Units', 19, 1),
    ('Outdoor', 'Outdoor Living', 'Units', 19, 2),
    ('Outdoor', 'Entertainment', 'Units', 19, 3),
    ('Garden Equipment', 'Gardening Tools', 'Units', 20, 0),
    ('Garden Equipment', 'Outdoor Maintenance', 'Units', 20, 1),
    ('Garden Equipment', 'Outdoor Living', 'Units', 20, 2),
    ('Garden Equipment', 'Entertainment', 'Units', 20, 3),
    ('Fitness Gear', 'Home Gym Basics', 'Units', 21, 0),
    ('Fitness Gear', 'Recovery', 'Units', 21, 1),
    ('Fitness Gear', 'Support', 'Units', 21, 2),
    ('Toys', 'Action Figures', 'Units', 22, 0),
    ('Toys', 'Playsets', 'Units', 22, 1),
    ('Toys', 'Building Blocks', 'Units', 22, 2),
    ('Toys', 'Construction', 'Units', 22, 3),
    ('Toys', 'Dolls', 'Units', 22, 4),
    ('Toys', 'Accessories', 'Units', 22, 5),
    ('Toys', 'Vehicles', 'Units', 22, 6),
    ('Toys', 'Remote Control', 'Units', 22, 7),
    ('Toys', 'Arts', 'Units', 22, 8),
    ('Toys', 'Crafts', 'Units', 22, 9),
    ('Toys', 'Board Games', 'Units', 22, 10),
    ('Toys', 'Puzzles', 'Units', 22, 11),
    ('Toys', 'Plush', 'Units', 22, 12),
    ('Toys', 'Stuffed Animals', 'Units', 22, 13),
    ('Toys', 'Educational', 'Units', 22, 14),
    ('Toys', 'STEM Toys', 'Units', 22, 15),
]
